"""empty message

Revision ID: 53764c448eea
Revises: b46c1b18502c
Create Date: 2020-04-26 10:41:29.472483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53764c448eea'
down_revision = 'b46c1b18502c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('option_id', sa.Integer(), nullable=True))
    op.drop_constraint('responses_choosen_option_fkey', 'responses', type_='foreignkey')
    op.create_foreign_key(None, 'responses', 'options', ['option_id'], ['id'])
    op.drop_column('responses', 'choosen_option')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('choosen_option', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.create_foreign_key('responses_choosen_option_fkey', 'responses', 'options', ['choosen_option'], ['id'])
    op.drop_column('responses', 'option_id')
    # ### end Alembic commands ###
